# Uncomment the next line to define a global platform for your project
platform :ios, '18.2'

target 'recycla' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for recycla
  pod 'GoogleSignIn'
  pod 'GoogleSignInSwiftSupport'
  pod 'Firebase'
  #pod 'FirebaseAuth'
  pod 'FirebaseUI'
  pod 'Firebase/Messaging'

end
